version: '3'

services:
  python-app:
    build: .
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/
    links:
      - mongo
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"